### PR TITLE
descriptive message added

### PR DESCRIPTION
**Pull request by dynamo63**
I added the descriptive message of the program and I also made a small fix in the README.md

### CODE REVIEW

**Comment by tuladhar** [comment]
Thanks, @dynamo63. Can you please exclude the changes to binary as we are working on automating binary building through Github Actions. Besides that PR looks good.

**Review by tuladhar — CHANGES_REQUESTED** [review]
Please exclude modification to the binary.

**Comment by dynamo63** [comment]
I put the old version back

**Review by tuladhar — APPROVED** [review]
Looks good! 👍

**Comment by tuladhar** [comment]
Thanks @dynamo63 for your contributions!

**Comment by dynamo63** [comment]
Please :yum:  , Can you label this PR **hacktoberfest-accepted** ? is it very important for me !

**Pull request merged**
